// Generated by ../../ingest.mjs — do not edit by hand.
// Runs `node toolkit/ingest.mjs` after you've captured fragments to populate this array from
// fragments/<id>/. It ships empty: each entry is a real screen-recording (video + event/caption
// timeline) copied into public/frag/<id>/ and described as a typed FragmentEntry. The final cut
// (final/cutlist.ts) references entries by `manifestId`, and Root.tsx registers a review
// composition per fragment×variant.
import type { FragmentEntry } from "./lib/types";

export const FRAGMENTS: FragmentEntry[] = [];
